drop table if exists public.produtos cascade;

create table public.produtos (
    id bigint generated by default as identity primary key,
    nome text not null,
    descricao text not null,
    preco numeric(10, 2) not null check (preco >= 0),
    preco_original numeric(10, 2) check (preco_original is null or preco_original > preco),
    imagem text not null default 'img/lirio2.webp',
    categoria text not null default 'Classicos',
    promocao boolean not null default false,
    criado_em timestamptz not null default now()
);

alter table public.produtos enable row level security;

create policy "catalogo publico leitura" on public.produtos
    for select to anon, authenticated using (true);

create policy "painel inserir produtos" on public.produtos
    for insert to anon, authenticated with check (true);

create policy "painel atualizar produtos" on public.produtos
    for update to anon, authenticated using (true) with check (true);

create policy "painel excluir produtos" on public.produtos
    for delete to anon, authenticated using (true);

insert into public.produtos (nome, descricao, preco, categoria, imagem) values
('Chocolate cremoso', 'Camadas de bolo de chocolate e creme de brigadeiro.', 12.00, 'Classicos', 'img/lirio2.webp'),
('Morango com creme', 'Bolo branco, creme suave e pedacos de morango.', 14.00, 'Frutados', 'img/lirio2.webp'),
('Limao refrescante', 'Massa leve com mousse de limao e raspas citricas.', 13.00, 'Frutados', 'img/lirio2.webp'),
('Leite Ninho', 'Bolo branco com creme de leite em po bem delicado.', 14.00, 'Especiais', 'img/lirio2.webp'),
('Pacoca crocante', 'Creme de amendoim, bolo macio e farofa de pacoca.', 13.00, 'Especiais', 'img/lirio2.webp'),
('Red velvet', 'Bolo aveludado com recheio cremoso de cream cheese.', 15.00, 'Especiais', 'img/lirio2.webp');
